### ISSUE TITLE
Possible PR

### ISSUE THREAD

**Issue by philipturner** [tensorush/Awesome-3D-Programming#1]
I will soon release a framework for making AR headset experiences on $5 Google Cardboard and an iPhone. Yes, I said AR, not VR. It will be very high-level and drastically lower the barrier for beginners to work with AR or Metal on iOS. Also, if anyone has Google Cardboard (which I'm sure some 3D graphics enthusiasts will), then they'll have access to the first affordable AR headset experience before smart glasses.

There's more information on [this article](https://philipturner.github.io/first-affordable-ar-headset). I also published a [research paper](https://github.com/philipturner/scene-color-reconstruction) on it and made a free iOS app, [AR MultiPendulum](https://github.com/philipturner/ar-multipendulum) (App Store link is in the repo). 

When it is released, would ARHeadsetKit be a viable addition to your repository?

**Comment by tensorush** [comment]
Hi, how awesome! Sure thing, you got it! I'll be on the lookout for the release, good luck 👍🏼

**Comment by tensorush** [comment]
And accepted! 😃
